import type { Metadata } from 'next';
import { outfitFont } from './fonts';
import './globals.css';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { SidebarProvider } from '@/components/ui/sidebar';
import SidebarPanel from '@/components/layout/sidebar-panel';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'TipTap',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        outfitFont.variable,
        'font-sans',
        inter.variable,
      )}
    >
      <body className={` ${outfitFont.className} min-h-full flex flex-col`}>
        <SidebarProvider>
          <SidebarPanel />
        </SidebarProvider>

        {children}
      </body>
    </html>
  );
}
